# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ChatDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChatDemo
  pod 'AFNetworking', '~> 3.2.1'
  pod 'DXPopover', '~> 0.1.1'
  pod 'Masonry', '~> 1.1.0'
  pod 'SDWebImage', '~> 5.0.0-beta3'
  
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
end
